#include "esp_event.h"

ESP_EVENT_DECLARE_BASE(PRC); // 公有事件
enum
{
    OTA_BEGIN_EVENT,
    OTA_COMPLETE_EVENT,
    STATE_LED_IDLE,
    STATE_LED_PENDING,
    PING_EVENT,
    MOTOR_DISABLE_LOCKED,
    OTA_PENDING,
    task_OTA,
    MOTOR_DISABLED,
};

ESP_EVENT_DECLARE_BASE(PRA); // Armour事件
enum
{
    PRA_STOP_EVENT,
    PRA_START_EVENT,
    PRA_HIT_EVENT,
    PRA_COMPLETE_EVENT,
    PRA_CONFIG_EVENT,
    PRA_CONFIG_DONE_EVENT,
};

ESP_EVENT_DECLARE_BASE(PRM); // 电机事件
enum
{
    PRM_UNLOCK_EVENT,
    PRM_NULOCK_DONE_EVENT,
    PRM_SPEED_STABLE_EVENT,
    PRM_START_EVENT,
    PRM_START_DONE_EVENT,
    PRM_STOP_EVENT,
    PRM_DISCONNECT_EVENT,
};